### ISSUE TITLE
ChallengeModeScreen.java issue with character mods

### ISSUE THREAD

**Issue by SabSparrow** [alexdriedger/ChallengeTheSpire#15]
The updateChallenges method in ChallengeModeScreen.java appears to be lacking the character offset adjustment
![image](https://user-images.githubusercontent.com/6931955/62430181-2f787680-b719-11e9-97ab-15df6fae233a.png)

**Comment by alexdriedger** [comment]
Thanks for submitting the issue. That is fixed in the latest update
