### ISSUE TITLE
FeatureRequest: Use Seed for Boss Rush

### ISSUE THREAD

**Issue by kxc0re** [alexdriedger/ChallengeTheSpire#5]
I don't know how open you are for FeatureRequests, but:

I think it would be a good idea to support Game-Seeds in the Creation of the Challenge Run, that way you could race/compete against other people on even grounds.

Let me know if it is in any way planned or possible, haven't looked to deep into the ModApi myself, if I have some time off i will search for a way myself.

**Comment by alexdriedger** [comment]
I like the idea! I'll add it to the road map

**Comment by alexdriedger** [comment]
You should be able to play Challenges from a Custom Run now, by selecting a challenge and a difficulty. In Custom Runs, you can set the seed. Hope this helps!
